CREATE TABLE IF NOT EXISTS PRODUCTS(
    P_ID TEXT , 
    P_NAME TEXT,
    S_ID TEXT,
    C_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);
INSERT INTO PRODUCTS(P_ID,P_NAME,S_ID,C_ID,UNIT,PRICE)
VALUES 
    ('1','Phone','1','1','12 BOXES * 20 BAGS',18),
    ('2','BOTTLES','2','2','1L * 10',29),
    ('3','TABLET','3','3','10 BOXES * 23 BAGS',99),
    ('4','TOY','4','4','12 BOXES * 10 BAGS',100),
    ('5','BOXERS','5','5','13',27);

SELECT COUNT (P_ID) AS P_COUNT
FROM PRODUCTS ;
SELECT AVG (PRICE) AS A_PRICE
FROM PRODUCTS ;
SELECT SUM (PRICE) AS T_PRICE 
FROM PRODUCTS ;